name: nssl Build

on:
  workflow_dispatch:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          9.0.x
    - name: Get Git Submodules
      run: git submodule update --init --recursive
    - name: Build
      run: dotnet build --configuration Release
    - name: Create Nuget Package
      run: dotnet pack -c Release -o ./artifacts
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'workflow_dispatch'
    - name: Deploy Nuget Package
      run: dotnet nuget push ./artifacts/'*.nupkg' -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      shell: bash
      if: matrix.os == 'ubuntu-latest' && github.event_name == 'workflow_dispatch'
