name: nssl Build

on:
  workflow_dispatch:
    inputs:
  push:
    branches:
      - master
jobs:
  build:
    env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix: 
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      if: matrix.os == 'ubuntu-latest'
    - uses: actions/checkout@v3
      with:
        fetch-depth: 1
      if: matrix.os != 'ubuntu-latest'
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: | 
          6.0.x
    - name: Get Git Submodules
      run: git submodule update --init --recursive
    - name: Build
      run: dotnet build --configuration Release
    - name: Create Nuget Package
      run: dotnet pack -c Release -o ./artifacts
      if: matrix.os == 'ubuntu-latest'
    - name: Deploy Nuget Package
      run: dotnet nuget push ./artifacts/'*.nupkg' -k $NUGET_API_KEY -s https://api.nuget.org/v3/index.json
      shell: bash
      if: matrix.os == 'ubuntu-latest'
